### ISSUE TITLE
テーブルヘッダーの固定

### ISSUE THREAD

**Issue by riko-okubo** [deBroglieeeen/DataQueen#30]
スクロールしてもテーブルのヘッダーは上に固定されるようにする。

**Comment by deBroglieeeen** [comment]
@riko-okubo 対応ありがとうございました！随分とDataQueenが使いやすくなりました

対応終わりましたらissue閉じるようによろしくお願い致します。

Thank you for your support! DataQueen is now much easier to use!
Please close the issue when you are done.
